version: "3.8"

services:
  db:
    image: postgres:alpine3.19
    container_name: gochat_db
    restart: unless-stopped
    ports:
      - "${DB_EXTERNAL_PORT}:${DB_INTERNAL_PORT}"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  server:
    container_name: gochat_server
    build:
      context: .
      dockerfile: ./apps/server/Dockerfile
      args:
        - SERVER_INTERNAL_PORT=${SERVER_INTERNAL_PORT}
    ports:
      - ${SERVER_EXTERNAL_PORT}:${SERVER_INTERNAL_PORT}
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - db
