root = "../.."
testdata_dir = "testdata"
tmp_dir = "dist"

[build]
  args_bin = []
  bin = "./dist/main_server"
  cmd = "go build -o ./dist/main_server ."
  # cmd = "cd ../.. && go run ./apps/server"
  delay = 200
  exclude_dir = ["assets", "dist", "tmp", "vendor", "testdata", "postgres_data", "**/node_modules", "**/dist"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go"]
  include_file = ["go.mod", "go.work", "go.sum"]
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  post_cmd = []
  pre_cmd = []
  rerun = false
  rerun_delay = 300
  send_interrupt = false
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true
